INFO:root:Webhook Response: {'status': 'webhook worked'}
INFO:talkingcharacter.views:updateview Methode aufgerufen
INFO:talkingcharacter.views:Erhaltener Link: https://d-id-talks-prod.s3.us-west-2.amazonaws.com/google-oauth2%7C113737039728929273410/tlk_X_L4Es_Oy83_ebJZ2hCul/1701540122921.mp4?AWSAccessKeyId=AKIA5CUMPJBIK65W6FGA&Expires=1701626526&Signature=xNGR%2F9qF3x5iFSn%2BOAKAaxFwbO0%3D&X-Amzn-Trace-Id=Root%3D1-656b711e-02053a266ea1de9d2a0a0488%3BParent%3D9bae3816aaaf5b70%3BSampled%3D1%3BLineage%3D6b931dd4%3A0
INFO:django.utils.autoreload:C:\Users\41796\Documents\GitHub\Maturaarbeit_TalkingCharacter\OnlineVersion\talkingcharacter\views.py changed, reloading.
INFO:root:Webhook Response: {'status': 'webhook worked'}
INFO:talkingcharacter.views:updateview Methode aufgerufen
INFO:talkingcharacter.views:Erhaltener Link: https://d-id-talks-prod.s3.us-west-2.amazonaws.com/google-oauth2%7C113737039728929273410/tlk_eWEwRVP6aCC1qCR_25cKo/1701540224119.mp4?AWSAccessKeyId=AKIA5CUMPJBIK65W6FGA&Expires=1701626627&Signature=9HHibod5PNjALRKJLNAvsWWUOIc%3D&X-Amzn-Trace-Id=Root%3D1-656b7182-66073ce01fd6c52977561b80%3BParent%3De9f67cb7e6b7626e%3BSampled%3D1%3BLineage%3D6b931dd4%3A0
WARNING:django.request:Not Found: /undefined
INFO:django.utils.autoreload:C:\Users\41796\Documents\GitHub\Maturaarbeit_TalkingCharacter\OnlineVersion\talkingcharacter\views.py changed, reloading.
INFO:root:Webhook Response: {'status': 'webhook worked'}
INFO:talkingcharacter.views:updateview Methode aufgerufen
INFO:talkingcharacter.views:Erhaltener Link: https://d-id-talks-prod.s3.us-west-2.amazonaws.com/google-oauth2%7C113737039728929273410/tlk_1Sk_5tKLXmYERkAS-H2Yi/1701540284532.mp4?AWSAccessKeyId=AKIA5CUMPJBIK65W6FGA&Expires=1701626687&Signature=svie2IaORtgca3SQUjSwKEM4zDs%3D&X-Amzn-Trace-Id=Root%3D1-656b71bf-2ec87d667c9bbcf1480585ca%3BParent%3D20279326aaa694af%3BSampled%3D1%3BLineage%3D6b931dd4%3A0
WARNING:django.request:Not Found: /undefined
INFO:django.utils.autoreload:C:\Users\41796\Documents\GitHub\Maturaarbeit_TalkingCharacter\OnlineVersion\talkingcharacter\views.py changed, reloading.
INFO:root:Webhook Response: {'status': 'webhook worked'}
INFO:talkingcharacter.views:updateview Methode aufgerufen
INFO:talkingcharacter.views:Erhaltener Link: https://d-id-talks-prod.s3.us-west-2.amazonaws.com/google-oauth2%7C113737039728929273410/tlk_eC7t9lBv8mr7QfTr53lLF/1701540494167.mp4?AWSAccessKeyId=AKIA5CUMPJBIK65W6FGA&Expires=1701626896&Signature=jOv46pcZ9%2FvNkxt7Kv%2FhWyAuOTo%3D&X-Amzn-Trace-Id=Root%3D1-656b7290-33da6d2f5c5eaa555a6aaeac%3BParent%3Dd8383a0a63f77e5a%3BSampled%3D1%3BLineage%3D6b931dd4%3A0
ERROR:django.request:Internal Server Error: /webhook/
Traceback (most recent call last):
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\decorators\http.py", line 43, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\Documents\GitHub\Maturaarbeit_TalkingCharacter\OnlineVersion\talkingcharacter\views.py", line 91, in WebhookReceiver
    CharacterView.updateview(link, request)
  File "C:\Users\41796\Documents\GitHub\Maturaarbeit_TalkingCharacter\OnlineVersion\talkingcharacter\views.py", line 56, in updateview
    return render("index.html", context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loaders\base.py", line 17, in get_template
    for origin in self.get_template_sources(template_name):
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loaders\cached.py", line 70, in get_template_sources
    yield from loader.get_template_sources(template_name)
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loaders\filesystem.py", line 35, in get_template_sources
    name = safe_join(template_dir, template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
                         ^^^^^^^^^^^^^^^^^^
  File "<frozen ntpath>", line 147, in join
  File "<frozen genericpath>", line 152, in _check_arg_types
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'dict'
INFO:django.utils.autoreload:C:\Users\41796\Documents\GitHub\Maturaarbeit_TalkingCharacter\OnlineVersion\talkingcharacter\views.py changed, reloading.
INFO:root:Webhook Response: {'status': 'webhook worked'}
INFO:talkingcharacter.views:updateview Methode aufgerufen
INFO:talkingcharacter.views:Erhaltener Link: https://d-id-talks-prod.s3.us-west-2.amazonaws.com/google-oauth2%7C113737039728929273410/tlk_wXsreGVHNjubPe_jXQbAn/1701540585508.mp4?AWSAccessKeyId=AKIA5CUMPJBIK65W6FGA&Expires=1701626988&Signature=lju3TiLmpw1Cvj0I5btKww1z4YE%3D&X-Amzn-Trace-Id=Root%3D1-656b72ec-0425c3a41281dfae16f6a203%3BParent%3Df7aeef5546e6322f%3BSampled%3D1%3BLineage%3D6b931dd4%3A0
ERROR:django.request:Internal Server Error: /webhook/
Traceback (most recent call last):
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\decorators\http.py", line 43, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\Documents\GitHub\Maturaarbeit_TalkingCharacter\OnlineVersion\talkingcharacter\views.py", line 91, in WebhookReceiver
    CharacterView.updateview(link, request)
  File "C:\Users\41796\Documents\GitHub\Maturaarbeit_TalkingCharacter\OnlineVersion\talkingcharacter\views.py", line 56, in updateview
    return render(template_name="index.html", context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: render() missing 1 required positional argument: 'request'
INFO:django.utils.autoreload:C:\Users\41796\Documents\GitHub\Maturaarbeit_TalkingCharacter\OnlineVersion\talkingcharacter\views.py changed, reloading.
INFO:root:Webhook Response: {'status': 'webhook worked'}
INFO:talkingcharacter.views:updateview Methode aufgerufen
INFO:talkingcharacter.views:Erhaltener Link: https://d-id-talks-prod.s3.us-west-2.amazonaws.com/google-oauth2%7C113737039728929273410/tlk_FnXd6RkKdDSFGby3121sg/1701540877516.mp4?AWSAccessKeyId=AKIA5CUMPJBIK65W6FGA&Expires=1701627280&Signature=dpUXn8sl1YH7J7vhcnsqVEFhk%2FI%3D&X-Amzn-Trace-Id=Root%3D1-656b7410-2bcc001434c8235d4a5eae9c%3BParent%3D4f0214433686e857%3BSampled%3D1%3BLineage%3D6b931dd4%3A0
INFO:django.utils.autoreload:C:\Users\41796\Documents\GitHub\Maturaarbeit_TalkingCharacter\OnlineVersion\talkingcharacter\views.py changed, reloading.
INFO:root:Webhook Response: {'status': 'webhook worked'}
INFO:talkingcharacter.views:updateview Methode aufgerufen
INFO:talkingcharacter.views:Erhaltener Link: https://d-id-talks-prod.s3.us-west-2.amazonaws.com/google-oauth2%7C113737039728929273410/tlk_72muHQTlUKTvOa-hQrAqB/1701540945094.mp4?AWSAccessKeyId=AKIA5CUMPJBIK65W6FGA&Expires=1701627347&Signature=Aa6SR1DP6vUmMjIX5M1IqL1TrC0%3D&X-Amzn-Trace-Id=Root%3D1-656b7453-12987db121c73411450ff1c1%3BParent%3D8f3e6ddfd05d4c56%3BSampled%3D1%3BLineage%3D6b931dd4%3A0
WARNING:django.request:Not Found: /undefined
INFO:django.utils.autoreload:C:\Users\41796\Documents\GitHub\Maturaarbeit_TalkingCharacter\OnlineVersion\talkingcharacter\views.py changed, reloading.
INFO:root:Webhook Response: {'status': 'webhook worked'}
INFO:talkingcharacter.views:updateview Methode aufgerufen
INFO:talkingcharacter.views:Erhaltener Link: https://d-id-talks-prod.s3.us-west-2.amazonaws.com/google-oauth2%7C113737039728929273410/tlk_Dmpr8rZV67IJXUiIVaOCM/1701541784401.mp4?AWSAccessKeyId=AKIA5CUMPJBIK65W6FGA&Expires=1701628186&Signature=Gq4su2ErciNSrKXtuE2PveI06Kw%3D&X-Amzn-Trace-Id=Root%3D1-656b779a-0917db6960c0b88c6ffa761e%3BParent%3D72bc419d83dd8cfb%3BSampled%3D1%3BLineage%3D6b931dd4%3A0
INFO:django.utils.autoreload:C:\Users\41796\Documents\GitHub\Maturaarbeit_TalkingCharacter\OnlineVersion\talkingcharacter\views.py changed, reloading.
INFO:root:Webhook Response: {'status': 'webhook worked'}
INFO:talkingcharacter.views:updateview Methode aufgerufen
INFO:talkingcharacter.views:Erhaltener Link bei  updateview: https://d-id-talks-prod.s3.us-west-2.amazonaws.com/google-oauth2%7C113737039728929273410/tlk_xM_51H96A9HuxaqZgI1ku/1701542138744.mp4?AWSAccessKeyId=AKIA5CUMPJBIK65W6FGA&Expires=1701628541&Signature=MVyVQ7Z8X0WQWacf0ofHCi%2BvNv8%3D&X-Amzn-Trace-Id=Root%3D1-656b78fd-75551f68572e4e2d24ed614d%3BParent%3D456f142cce6762bb%3BSampled%3D1%3BLineage%3D6b931dd4%3A0
INFO:django.utils.autoreload:C:\Users\41796\Documents\GitHub\Maturaarbeit_TalkingCharacter\OnlineVersion\talkingcharacter\views.py changed, reloading.
INFO:root:Webhook Response: {'status': 'webhook worked'}
INFO:talkingcharacter.views:updateview Methode aufgerufen
INFO:talkingcharacter.views:Erhaltener Link bei  updateview: https://d-id-talks-prod.s3.us-west-2.amazonaws.com/google-oauth2%7C113737039728929273410/tlk_FRFmYhv-YffNy4xp4F6XV/1701542389368.mp4?AWSAccessKeyId=AKIA5CUMPJBIK65W6FGA&Expires=1701628791&Signature=nB8f%2B3zyUUCpigp1MSV9x7IsNnI%3D&X-Amzn-Trace-Id=Root%3D1-656b79f7-6bf4b98d7fd4e745052570f1%3BParent%3D41f46a9d3fcbc40b%3BSampled%3D1%3BLineage%3D6b931dd4%3A0
WARNING:django.request:Not Found: /undefined
INFO:django.utils.autoreload:C:\Users\41796\Documents\GitHub\Maturaarbeit_TalkingCharacter\OnlineVersion\talkingcharacter\views.py changed, reloading.
INFO:root:Webhook Response: {'status': 'webhook worked'}
INFO:talkingcharacter.views:updateview Methode aufgerufen
INFO:talkingcharacter.views:Erhaltener Link bei  updateview: https://d-id-talks-prod.s3.us-west-2.amazonaws.com/google-oauth2%7C113737039728929273410/tlk_e1-lqRNAyecTwlNGlMsbv/1701542631364.mp4?AWSAccessKeyId=AKIA5CUMPJBIK65W6FGA&Expires=1701629033&Signature=fkuaSAjDVU50YOyzKVms63XkTHI%3D&X-Amzn-Trace-Id=Root%3D1-656b7ae9-4162caf44966d1ed09edd8da%3BParent%3Dd5e5db376aa77662%3BSampled%3D1%3BLineage%3D6b931dd4%3A0
INFO:django.utils.autoreload:C:\Users\41796\Documents\GitHub\Maturaarbeit_TalkingCharacter\OnlineVersion\talkingcharacter\views.py changed, reloading.
INFO:root:Webhook Response: {'status': 'webhook worked'}
ERROR:django.request:Internal Server Error: /webhook/
Traceback (most recent call last):
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\decorators\http.py", line 43, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\Documents\GitHub\Maturaarbeit_TalkingCharacter\OnlineVersion\talkingcharacter\views.py", line 113, in WebhookReceiver
    CharacterView.updateview(link, request)
    ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'CharacterView' has no attribute 'updateview'
INFO:django.utils.autoreload:C:\Users\41796\Documents\GitHub\Maturaarbeit_TalkingCharacter\OnlineVersion\talkingcharacter\views.py changed, reloading.
INFO:root:Webhook Response: {'status': 'webhook worked'}
ERROR:django.request:Internal Server Error: /webhook/
Traceback (most recent call last):
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\decorators\http.py", line 43, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\Documents\GitHub\Maturaarbeit_TalkingCharacter\OnlineVersion\talkingcharacter\views.py", line 113, in WebhookReceiver
    CharacterView.get_context_data(link, request)
TypeError: CharacterView.get_context_data() takes 1 positional argument but 2 were given
INFO:django.utils.autoreload:C:\Users\41796\Documents\GitHub\Maturaarbeit_TalkingCharacter\OnlineVersion\talkingcharacter\views.py changed, reloading.
INFO:root:Webhook Response: {'status': 'webhook worked'}
ERROR:django.request:Internal Server Error: /webhook/
Traceback (most recent call last):
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\decorators\http.py", line 43, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\Documents\GitHub\Maturaarbeit_TalkingCharacter\OnlineVersion\talkingcharacter\views.py", line 113, in WebhookReceiver
    CharacterView.get_context_data(link)
  File "C:\Users\41796\Documents\GitHub\Maturaarbeit_TalkingCharacter\OnlineVersion\talkingcharacter\views.py", line 50, in get_context_data
    context = super().get_context_data(**kwargs)
              ^^^^^^^
TypeError: super(type, obj): obj must be an instance or subtype of type
INFO:django.utils.autoreload:C:\Users\41796\Documents\GitHub\Maturaarbeit_TalkingCharacter\OnlineVersion\talkingcharacter\views.py changed, reloading.
INFO:root:Webhook Response: {'status': 'webhook worked'}
ERROR:django.request:Internal Server Error: /webhook/
Traceback (most recent call last):
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\decorators\http.py", line 43, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\Documents\GitHub\Maturaarbeit_TalkingCharacter\OnlineVersion\talkingcharacter\views.py", line 115, in WebhookReceiver
    CharacterView.get_context_data(link)
  File "C:\Users\41796\Documents\GitHub\Maturaarbeit_TalkingCharacter\OnlineVersion\talkingcharacter\views.py", line 51, in get_context_data
    context = super().get_context_data(**kwargs)
              ^^^^^^^
TypeError: super(type, obj): obj must be an instance or subtype of type
INFO:django.utils.autoreload:C:\Users\41796\Documents\GitHub\Maturaarbeit_TalkingCharacter\OnlineVersion\talkingcharacter\views.py changed, reloading.
INFO:root:Webhook Response: {'status': 'webhook worked'}
ERROR:django.request:Internal Server Error: /webhook/
Traceback (most recent call last):
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\decorators\http.py", line 43, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\Documents\GitHub\Maturaarbeit_TalkingCharacter\OnlineVersion\talkingcharacter\views.py", line 115, in WebhookReceiver
    CharacterView.get_context_data(link)
  File "C:\Users\41796\Documents\GitHub\Maturaarbeit_TalkingCharacter\OnlineVersion\talkingcharacter\views.py", line 51, in get_context_data
    context = super().get_context_data(**kwargs)
              ^^^^^^^
TypeError: super(type, obj): obj must be an instance or subtype of type
INFO:django.utils.autoreload:C:\Users\41796\Documents\GitHub\Maturaarbeit_TalkingCharacter\OnlineVersion\talkingcharacter\views.py changed, reloading.
INFO:root:Webhook Response: {'status': 'webhook worked'}
WARNING:django.request:Not Found: /undefined
INFO:root:Webhook Response: {'status': 'webhook worked'}
WARNING:django.request:Not Found: /undefined
INFO:root:Webhook Response: {'status': 'webhook worked'}
INFO:root:Webhook Response: {'status': 'webhook worked'}
WARNING:django.request:Not Found: /undefined
WARNING:django.request:Not Found: /favicon.ico
INFO:root:Webhook Response: {'status': 'webhook worked'}
INFO:root:Webhook Response: {'status': 'webhook worked'}
WARNING:django.request:Not Found: /link.link@link.com
INFO:django.utils.autoreload:C:\Users\41796\Documents\GitHub\Maturaarbeit_TalkingCharacter\OnlineVersion\talkingcharacter\views.py changed, reloading.
INFO:root:Webhook Response: {'status': 'webhook worked'}
ERROR:django.request:Internal Server Error: /webhook/
Traceback (most recent call last):
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\decorators\http.py", line 43, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\Documents\GitHub\Maturaarbeit_TalkingCharacter\OnlineVersion\talkingcharacter\views.py", line 120, in WebhookReceiver
    return JsonResponse({'request': saverequest, 'status':'webhook worked', 'video_link': link}, safe=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\http\response.py", line 748, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\serializers\json.py", line 106, in default
    return super().default(o)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type WSGIRequest is not JSON serializable
WARNING:django.request:Not Found: /path_to_your_video_link_endpoint/
WARNING:django.request:Not Found: /link.link@link.com
INFO:root:Webhook Response: {'status': 'webhook worked'}
ERROR:django.request:Internal Server Error: /webhook/
Traceback (most recent call last):
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\decorators\http.py", line 43, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\Documents\GitHub\Maturaarbeit_TalkingCharacter\OnlineVersion\talkingcharacter\views.py", line 120, in WebhookReceiver
    return JsonResponse({'request': saverequest, 'status':'webhook worked', 'video_link': link}, safe=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\http\response.py", line 748, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\serializers\json.py", line 106, in default
    return super().default(o)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type WSGIRequest is not JSON serializable
INFO:django.utils.autoreload:C:\Users\41796\Documents\GitHub\Maturaarbeit_TalkingCharacter\OnlineVersion\talkingcharacter\views.py changed, reloading.
INFO:root:Webhook Response: {'status': 'webhook worked'}
INFO:django.utils.autoreload:C:\Users\41796\Documents\GitHub\Maturaarbeit_TalkingCharacter\OnlineVersion\main\settings.py changed, reloading.
INFO:root:Webhook Response: {'status': 'webhook worked'}
ERROR:django.request:Internal Server Error: /webhook/
Traceback (most recent call last):
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\decorators\http.py", line 43, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\Documents\GitHub\Maturaarbeit_TalkingCharacter\OnlineVersion\talkingcharacter\views.py", line 127, in WebhookReceiver
    'video_url': new_video_url
                 ^^^^^^^^^^^^^
NameError: name 'new_video_url' is not defined
WARNING:django.request:Not Found: /link.link@link.com
INFO:django.utils.autoreload:C:\Users\41796\Documents\GitHub\Maturaarbeit_TalkingCharacter\OnlineVersion\talkingcharacter\views.py changed, reloading.
INFO:root:Webhook Response: {'status': 'webhook worked'}
ERROR:django.request:Internal Server Error: /webhook/
Traceback (most recent call last):
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\redis\asyncio\connection.py", line 243, in connect
    await self.retry.call_with_retry(
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\redis\asyncio\retry.py", line 59, in call_with_retry
    return await do()
           ^^^^^^^^^^
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\redis\asyncio\connection.py", line 650, in _connect
    reader, writer = await asyncio.open_connection(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\asyncio\streams.py", line 48, in open_connection
    transport, _ = await loop.create_connection(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1085, in create_connection
    raise exceptions[0]
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1069, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 973, in _connect_sock
    await self.sock_connect(sock, address)
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\asyncio\proactor_events.py", line 726, in sock_connect
    return await self._proactor.connect(sock, address)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 846, in _poll
    value = callback(transferred, key, ov)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 633, in finish_connect
    ov.getresult()
ConnectionRefusedError: [WinError 1225] The remote computer refused the network connection

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\decorators\http.py", line 43, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\Documents\GitHub\Maturaarbeit_TalkingCharacter\OnlineVersion\talkingcharacter\views.py", line 123, in WebhookReceiver
    async_to_sync(channel_layer.group_send)(
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 240, in __call__
    return call_result.result()
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 306, in main_wrap
    result = await self.awaitable(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\channels_redis\core.py", line 523, in group_send
    await connection.zremrangebyscore(
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\redis\asyncio\client.py", line 601, in execute_command
    conn = self.connection or await pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\redis\asyncio\connection.py", line 1040, in get_connection
    await self.ensure_connection(connection)
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\redis\asyncio\connection.py", line 1062, in ensure_connection
    await connection.connect()
  File "C:\Users\41796\AppData\Local\Programs\Python\Python311\Lib\site-packages\redis\asyncio\connection.py", line 251, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 22 connecting to 127.0.0.1:6379. 22.
WARNING:django.request:Not Found: /link.link@link.com
INFO:root:Webhook Response: {'status': 'webhook worked'}
